apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: nichol20/microservices-python-gateway:latest
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: gateway-configmap
          - secretRef:
              name: gateway-secret
